### PR TITLE
Add tiny-invariant suggestion

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by taion** [comment]
Thanks!

**Comment by taion** [comment]
Though I’ll note that the normal invariant is likely faster, since it generally would save the cost of string formatting when the invariant passes.

**Comment by TrySound** [comment]
Sorry, I didn't get how tiny-invariant is slower?
invariant:
image
tiny-invariant:
image

**Comment by TrySound** [comment]
Where?
image

**Comment by taion** [comment]
Compare:

```js
invariant(foo === 'bar', 'foo was %s, not "bar"', foo);
```

to:

```js
invariant(foo === 'bar', `foo was ${foo}, not "bar"`);
```

The latter will _always_ interpolate the value of `foo` into the string. The former will not do the interpolation unless the invariant condition fails.

**Comment by TrySound** [comment]
Well, that's fine.

**Pull request merged**
